# Default values for ospo-app.
# This is a YAML-formatted file.

replicaCount: 1

# Image configuration for app container
app:
  image:
    repository: ospo-events-app
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    NODE_ENV: production
    PORT: "5000"
    SESSION_SECRET: "ospo-session-secret-123"
    SESSION_STORE_TYPE: "memory"
    VITE_SERVE_CLIENT: "true"
    KEYCLOAK_CLIENT_ID: "ospo-events-app"
    KEYCLOAK_CLIENT_SECRET: "client-secret-123"

# PostgreSQL configuration
postgresql:
  enabled: true
  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
  auth:
    username: ospo_user
    password: ospo_password123
    database: ospo_events
  service:
    port: 5432
  persistence:
    enabled: false
    size: 1Gi

# Keycloak configuration
keycloak:
  enabled: true
  image:
    repository: quay.io/keycloak/keycloak
    tag: 23.0.6
    pullPolicy: IfNotPresent
  admin:
    username: admin
    password: admin
  realm: ospo-events
  service:
    port: 8080
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# MinIO configuration
minio:
  enabled: true
  image:
    repository: minio/minio
    tag: RELEASE.2024-04-29T01-14-24Z
    pullPolicy: IfNotPresent
  mc:
    image:
      repository: minio/mc
      tag: RELEASE.2024-04-29T18-08-57Z
      pullPolicy: Always
  auth:
    rootUser: minioadmin
    rootPassword: minioadmin
  buckets:
    - name: uploads
      policy: download
  service:
    apiPort: 9000
    consolePort: 9001
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

# LoadBalancer configuration
loadBalancer:
  enabled: true
  port: 7777
  targetPort: 5000

# Shared volume configuration
sharedVolume:
  enabled: true
  persistentVolumeClaim:
    enabled: false
    name: ospo-uploads-pvc
    size: 1Gi