services:
  # PostgreSQL Database (Internal Only)
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    # No external ports - only accessible within Docker network
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ospo_user -d ospo_events"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ospo-network

  # Keycloak Authentication Server (Internal Only)
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME_URL: http://localhost:4576/auth
      KC_HOSTNAME_ADMIN_URL: http://localhost:4576/auth
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HTTP_RELATIVE_PATH: /auth
      KC_PROXY: edge
      KC_PROXY_ADDRESS_FORWARDING: true
      KC_FRONTEND_URL: http://localhost:4576/auth
      KEYCLOAK_FRONTEND_URL: http://localhost:4576/auth
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KEYCLOAK_IMPORT_STRATEGY: OVERWRITE_EXISTING
    volumes:
      - ./keycloak-realm-export.json:/opt/keycloak/data/import/realm.json
    # No external ports - only accessible via nginx proxy
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/opt/keycloak/bin/kc.sh", "show-config"]
      interval: 45s
      timeout: 20s
      retries: 15
      start_period: 180s
    networks:
      - ospo-network

  # OSPO Application
  ospo-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_KEYCLOAK_URL: /auth
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      PGUSER: ${PGUSER}
      PGHOST: ${PGHOST}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      VITE_KEYCLOAK_URL: /auth
    volumes:
      - ./uploads:/app/public/uploads
    expose:
      - "4576"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4576/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - ospo-network

  # Nginx Reverse Proxy (Ingress)
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: >
      sh -c "rm -f /etc/nginx/conf.d/default.conf &&
             nginx -g 'daemon off;'"
    ports:
      - "4576:80"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      ospo-app:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - ospo-network

volumes:
  postgres_data:

networks:
  ospo-network:
    driver: bridge
