apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-code
  labels:
    app: {{ .Release.Name }}-app
    {{- include "ospo-app.labels" . | nindent 4 }}
data:
  "package.json": |
    {
      "name": "ospo-events-app",
      "version": "1.0.0",
      "main": "server/index.js",
      "scripts": {
        "start": "echo 'Starting application in fallback mode. Running with base image.'"
      },
      "dependencies": {
        "express": "^4.18.2"
      }
    }
  "index.js": |
    const express = require('express');
    const app = express();
    const port = process.env.PORT || 5000;

    app.get('/api/health', (req, res) => {
      res.json({ status: 'healthy', message: 'Application is running in fallback mode' });
    });

    app.listen(port, '0.0.0.0', () => {
      console.log(`Fallback server listening on port ${port}`);
    });