apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-scripts
  labels:
    app: {{ .Release.Name }}-app
    {{- include "ospo-app.labels" . | nindent 4 }}
data:
  app-entrypoint.sh: |-
{{ .Files.Get "files/app-entrypoint.sh" | indent 4 }}