apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-config
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
data:
  # Base URL for the application
  APP_BASE_URL: "https://{{ index .Values.ingress.hosts 0 "host" }}"
  
  # File upload settings
  FILE_UPLOAD_MAX_SIZE: "10485760"  # 10MB
  FILE_UPLOAD_PATH: "{{ .Values.sharedVolume.mountPath | default "/app/uploads" }}"
  
  # Keycloak configuration
  KEYCLOAK_REALM: "ospo"
  KEYCLOAK_CLIENT_ID: "ospo-app"
  KEYCLOAK_URL: "https://{{ index .Values.ingress.hosts 0 "host" }}/auth"
  
  # Log level
  LOG_LEVEL: "info"