apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}-app
    {{- include "ospo-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.appServer.service.type }}
  ports:
    - port: {{ .Values.appServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-app
    {{- include "ospo-app.selectorLabels" . | nindent 4 }}