apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    app: {{ .Release.Name }}-keycloak
    {{- include "ospo-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-keycloak
      {{- include "ospo-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-keycloak
        {{- include "ospo-app.selectorLabels" . | nindent 8 }}
      annotations:
        # Add timestamp annotation to force update on image rebuild
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          command: 
            - "/opt/keycloak/bin/kc.sh"
            - "start-dev"
            - "--db=postgres"
            - "--transaction-xa-enabled=false"
            - "--db-dialect=postgres"
            - "--optimized"
            - "--import-realm"
          ports:
            - name: http
              containerPort: {{ .Values.keycloak.service.port }}
              protocol: TCP
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.auth.adminUser }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "ospo-app.keycloak.secretName" . }}
                  key: {{ .Values.keycloak.auth.secretKeys.adminPasswordKey }}
            # Add transaction XA disabled flag
            - name: KC_TRANSACTION_XA_ENABLED
              value: "false"
            {{- range .Values.keycloak.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.keycloak.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /opt/keycloak/data
            - name: import
              mountPath: /opt/keycloak/data/import
              readOnly: true
          # Use startup probe to give Keycloak time to initialize
          startupProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: data
          {{- if .Values.keycloak.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-keycloak-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: import
          configMap:
            name: {{ .Release.Name }}-keycloak-realm