apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-realm
  labels:
    app: {{ .Release.Name }}-keycloak
    {{- include "ospo-app.labels" . | nindent 4 }}
data:
  # A basic initial realm configuration for Keycloak
  ospo-realm.json: |
    {
      "realm": "ospo-events",
      "enabled": true,
      "displayName": "OSPO Event Management",
      "displayNameHtml": "<div class=\"kc-logo-text\"><span>OSPO Event Management</span></div>",
      "sslRequired": "external",
      "registrationAllowed": true,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": true,
      "editUsernameAllowed": false,
      "bruteForceProtected": true,
      "defaultRoles": ["user"],
      "roles": {
        "realm": [
          {
            "name": "user",
            "description": "Regular user with standard permissions"
          },
          {
            "name": "admin",
            "description": "Administrative user with full access"
          },
          {
            "name": "event-manager",
            "description": "User can manage events"
          },
          {
            "name": "reviewer",
            "description": "User can review approval workflows"
          }
        ]
      },
      "clients": [
        {
          "clientId": "ospo-events-app",
          "name": "OSPO Event Management App",
          "enabled": true,
          "publicClient": true,
          "redirectUris": ["*"],
          "webOrigins": ["*"],
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": false,
          "fullScopeAllowed": true
        }
      ]
    }