apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-db-config
  labels:
    app: {{ .Release.Name }}-keycloak
    {{- include "ospo-app.labels" . | nindent 4 }}
data:
  # We need to create these configs for Keycloak to properly use Postgres without SQL compatibility issues
  postgres-concat.sql: |
    -- Create proper replacement for CONCAT function in PostgreSQL 
    -- This addresses the Liquibase migration issue with credential data

    -- Create a function to concatenate strings
    CREATE OR REPLACE FUNCTION custom_concat(VARIADIC text[]) 
    RETURNS text AS $$
    BEGIN
      RETURN concat_ws('', VARIADIC $1);
    END;
    $$ LANGUAGE plpgsql;

    -- Create an alias for CONCAT
    CREATE OR REPLACE FUNCTION CONCAT(VARIADIC text[]) 
    RETURNS text AS $$
    BEGIN
      RETURN concat_ws('', VARIADIC $1);
    END;
    $$ LANGUAGE plpgsql;