# PostgreSQL credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-credentials
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ "ospo_password123" | b64enc | quote }}
  password: {{ "ospo_password123" | b64enc | quote }}
  database-url: {{ printf "postgresql://ospo_user:ospo_password123@%s-postgresql:5432/ospo_events" .Release.Name | b64enc | quote }}
---
# Keycloak credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-credentials
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ "admin123" | b64enc | quote }}
  client-secret: {{ "client123456789" | b64enc | quote }}
---
# MinIO credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-credentials
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ "minio123" | b64enc | quote }}
  access-key: {{ "minio" | b64enc | quote }}
  secret-key: {{ "minio123" | b64enc | quote }}
---
# App secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secrets
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
type: Opaque
data:
  session-secret: {{ "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6" | b64enc | quote }}