{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
data:
  realm.json: |-
    {
      "realm": "{{ .Values.keycloak.realm }}",
      "enabled": true,
      "sslRequired": "external",
      "registrationAllowed": true,
      "registrationEmailAsUsername": false,
      "rememberMe": true,
      "verifyEmail": false,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": true,
      "editUsernameAllowed": false,
      "bruteForceProtected": true,
      "clients": [
        {
          "clientId": "{{ .Values.app.env.KEYCLOAK_CLIENT_ID }}",
          "enabled": true,
          "publicClient": true,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": false,
          "redirectUris": [
            "{{ .Values.app.baseUrl | default "https://*" }}/*",
            "{{ .Values.app.baseUrl | default "https://*" }}"
          ],
          "webOrigins": [
            "{{ .Values.app.baseUrl | default "https://*" }}"
          ],
          "protocol": "openid-connect",
          "frontchannelLogout": true,
          "fullScopeAllowed": true,
          "attributes": {
            "pkce.code.challenge.method": "S256"
          },
          "protocolMappers": [
            {
              "name": "username",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-property-mapper",
              "consentRequired": false,
              "config": {
                "userinfo.token.claim": "true",
                "user.attribute": "username",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "preferred_username",
                "jsonType.label": "String"
              }
            },
            {
              "name": "email",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-property-mapper",
              "consentRequired": false,
              "config": {
                "userinfo.token.claim": "true",
                "user.attribute": "email",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "email",
                "jsonType.label": "String"
              }
            }
          ],
          "defaultClientScopes": ["web-origins", "acr", "roles", "profile", "email"],
          "optionalClientScopes": ["address", "phone", "offline_access", "microprofile-jwt"]
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "user",
            "description": "Regular user role"
          },
          {
            "name": "admin",
            "description": "Administrator role"
          }
        ]
      },
      "defaultRoles": ["user"]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-client-config
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
data:
  keycloak.json: |-
    {
      "realm": "{{ .Values.keycloak.realm }}",
      "auth-server-url": "{{ .Values.keycloak.publicUrl | default (printf "https://%s-keycloak-%s.%s/auth" .Release.Name .Release.Namespace .Values.openshift.domain) }}",
      "ssl-required": "external",
      "resource": "{{ .Values.app.env.KEYCLOAK_CLIENT_ID }}",
      "public-client": true,
      "confidential-port": 0,
      "verify-token-audience": false,
      "use-resource-role-mappings": true,
      "enable-cors": true
    }
{{- end }}