{{- if .Values.nodePort.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: direct-ospo-app
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: direct-access
spec:
  type: NodePort
  ports:
    - port: {{ .Values.app.service.port }}
      nodePort: {{ .Values.nodePort.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ospo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: application
{{- end }}