{{- if .Values.keycloak.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ospo-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: auth
  template:
    metadata:
      labels:
        {{- include "ospo-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: auth
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:{{ .Values.postgresql.image.tag }}
          command: ['sh', '-c', 'until pg_isready -h postgres -p 5432; do echo "Waiting for postgres..."; sleep 2; done;']
      containers:
        - name: keycloak
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          args:
            - start
            - --optimized
            - --import-realm
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY
              value: "edge"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL_HOST
              value: "postgres"
            - name: KC_DB_URL_PORT
              value: "5432"
            - name: KC_DB_URL_DATABASE
              value: {{ .Values.postgresql.auth.database }}
            - name: KC_DB_USERNAME
              value: {{ .Values.postgresql.auth.username }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.admin.username }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.keycloak.admin.password }}
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_FEATURES
              value: "admin-api,account-api,account2,admin2,docker,impersonation,token-exchange,web-authn"
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import
          resources:
            {{- toYaml .Values.keycloak.resources | nindent 12 }}
      volumes:
        - name: realm-config
          configMap:
            name: keycloak-realm-config
            items:
              - key: ospo-realm.json
                path: ospo-realm.json
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  ports:
    - port: {{ .Values.keycloak.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ospo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: auth
{{- end }}