{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  annotations:
    "helm.sh/hook-weight": "-5"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ospo-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: storage
  template:
    metadata:
      labels:
        {{- include "ospo-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: storage
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.auth.rootUser }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.minio.auth.rootPassword }}
            - name: MINIO_DEFAULT_BUCKETS
              value: "uploads:download"
          ports:
            - name: api
              containerPort: {{ .Values.minio.service.apiPort }}
              protocol: TCP
            - name: console
              containerPort: {{ .Values.minio.service.consolePort }}
              protocol: TCP
          volumeMounts:
            - name: minio-data
              mountPath: /data
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
      volumes:
        - name: minio-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  ports:
    - port: {{ .Values.minio.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.minio.service.consolePort }}
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "ospo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: storage
---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage-setup
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        {{- include "ospo-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: storage-setup
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: "{{ .Values.minio.mc.image.repository }}:{{ .Values.minio.mc.image.tag }}"
          imagePullPolicy: {{ .Values.minio.mc.image.pullPolicy }}
          env:
            - name: MINIO_SERVER_HOST
              value: minio
            - name: MINIO_SERVER_PORT_NUMBER
              value: "{{ .Values.minio.service.apiPort }}"
            - name: MINIO_SERVER_ACCESS_KEY
              value: {{ .Values.minio.auth.rootUser }}
            - name: MINIO_SERVER_SECRET_KEY
              value: {{ .Values.minio.auth.rootPassword }}
            - name: MC_HOST_myminio
              value: "http://{{ .Values.minio.auth.rootUser }}:{{ .Values.minio.auth.rootPassword }}@minio:{{ .Values.minio.service.apiPort }}"
          command:
            - /bin/sh
            - -c
          args:
            - |
              sleep 15
              echo "Waiting for MinIO to become available..."
              # Create buckets and set policies
              {{- range .Values.minio.buckets }}
              echo "Creating bucket {{ .name }}..."
              mc mb --ignore-existing myminio/{{ .name }} || echo "Bucket already exists or creation failed"
              {{- if eq .policy "download" }}
              echo "Setting download policy for {{ .name }}..."
              mc policy set download myminio/{{ .name }} || echo "Policy setting failed"
              {{- else if eq .policy "upload" }}
              echo "Setting upload policy for {{ .name }}..."
              mc policy set upload myminio/{{ .name }} || echo "Policy setting failed"
              {{- else if eq .policy "public" }}
              echo "Setting public policy for {{ .name }}..."
              mc policy set public myminio/{{ .name }} || echo "Policy setting failed"
              {{- end }}
              {{- end }}
              echo "MinIO setup completed"
{{- end }}