{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ospo-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: storage
  template:
    metadata:
      labels:
        {{- include "ospo-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: storage
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          args:
            - server
            - /data
            - --console-address
            - ":{{ .Values.minio.service.consolePort }}"
          ports:
            - name: api
              containerPort: {{ .Values.minio.service.apiPort }}
              protocol: TCP
            - name: console
              containerPort: {{ .Values.minio.service.consolePort }}
              protocol: TCP
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.auth.rootUser }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.minio.auth.rootPassword }}
          volumeMounts:
            - name: minio-data
              mountPath: /data
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
      volumes:
        - name: minio-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  ports:
    - port: {{ .Values.minio.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.minio.service.consolePort }}
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "ospo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: storage
---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage-setup
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        {{- include "ospo-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: storage-setup
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: "{{ .Values.minio.mc.image.repository }}:{{ .Values.minio.mc.image.tag }}"
          imagePullPolicy: {{ .Values.minio.mc.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
          args:
            - |
              sleep 5
              mc alias set myminio http://minio:{{ .Values.minio.service.apiPort }} {{ .Values.minio.auth.rootUser }} {{ .Values.minio.auth.rootPassword }}
              {{- range .Values.minio.buckets }}
              mc mb --ignore-existing myminio/{{ .name }}
              {{- if eq .policy "download" }}
              mc anonymous set download myminio/{{ .name }}
              {{- else if eq .policy "upload" }}
              mc anonymous set upload myminio/{{ .name }}
              {{- else if eq .policy "public" }}
              mc anonymous set public myminio/{{ .name }}
              {{- end }}
              {{- end }}
{{- end }}