{{- if .Values.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ospo-app.fullname" . }}-nodeport
  labels:
    {{- include "ospo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: nodeport
spec:
  type: NodePort
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      nodePort: {{ .Values.nodePort.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "ospo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: application
{{- end }}