apiVersion: batch/v1
kind: Job
metadata:
  name: csv-import-job
  namespace: prod-rh-events-org
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: csv-importer
        image: image-registry.openshift-image-registry.svc:5000/prod-rh-events-org/ospo-events-app:latest
        command: ["npx", "tsx", "scripts/import-csv-events.ts"]
        env:
        - name: CSV_FILE_PATH
          value: "/tmp/csv/events.csv"
        - name: KUBERNETES_SERVICE_HOST
          value: "kubernetes.default.svc"
        - name: PGHOST
          value: "postgres.prod-rh-events-org.svc.cluster.local"
        - name: PGPORT
          value: "5432"
        - name: PGDATABASE
          value: "ospo_events"
        - name: PGUSER
          value: "ospo_user"
        - name: PGPASSWORD
          value: "ospo_password_change_me"
        - name: NODE_ENV
          value: "production"
        volumeMounts:
        - name: csv-data
          mountPath: /tmp/csv
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: csv-data
        configMap:
          name: csv-import-data
          items:
          - key: events.csv
            path: events.csv
      securityContext:
        runAsNonRoot: true