apiVersion: apps/v1
kind: Deployment
metadata:
  name: ospo-app-direct
  labels:
    app: ospo-app-direct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ospo-app-direct
  template:
    metadata:
      labels:
        app: ospo-app-direct
    spec:
      containers:
        - name: ospo-app
          image: ospo-events-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "5000"
            - name: HOST
              value: "0.0.0.0"
            - name: VITE_SERVE_CLIENT
              value: "true"
            - name: DATABASE_URL
              value: "postgresql://ospo_user:ospo_password123@postgres:5432/ospo_events"
            - name: PGUSER
              value: "ospo_user"
            - name: PGHOST
              value: "postgres"
            - name: PGPASSWORD
              value: "ospo_password123"
            - name: PGDATABASE
              value: "ospo_events"
            - name: PGPORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: ospo-app-direct
  labels:
    app: ospo-app-direct
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ospo-app-direct
---
apiVersion: v1
kind: Service
metadata:
  name: ospo-app-nodeport
  labels:
    app: ospo-app-direct
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30777
      protocol: TCP
      name: web
  selector:
    app: ospo-app-direct