apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-client-config
  namespace: prod-rh-events-org
data:
  keycloak.json: |
    {
      "realm": "ospo-events",
      "auth-server-url": "https://ospo-events-ospo-app-prod-rh-events-org.apps.ospo-osci.z3b1.p1.openshiftapps.com/auth",
      "ssl-required": "external",
      "resource": "ospo-events-app",
      "public-client": false,
      "credentials": {
        "secret": "ospo-client-secret-change-me"
      },
      "confidential-port": 0,
      "policy-enforcer": {}
    }