apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-db-init
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: keycloak-db-init
        image: quay.io/keycloak/keycloak:23.0.6
        command: ["/bin/bash", "-c"]
        args:
        - |
          echo "Initializing Keycloak database schema..."
          export KC_DB=postgres
          export KC_DB_URL=jdbc:postgresql://postgres:5432/ospo_events
          export KC_DB_USERNAME=ospo_user
          export KC_DB_PASSWORD=ospo_password123
          
          # Run database migration
          /opt/keycloak/bin/kc.sh build --db=postgres
          
          echo "Keycloak database initialization completed"