apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
data:
  realm.json: |
    {
      "realm": "ospo-events",
      "enabled": true,
      "registrationAllowed": true,
      "registrationEmailAsUsername": false,
      "rememberMe": true,
      "verifyEmail": false,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": true,
      "editUsernameAllowed": false,
      "bruteForceProtected": true,
      "permanentLockout": false,
      "maxFailureWaitSeconds": 900,
      "minimumQuickLoginWaitSeconds": 60,
      "waitIncrementSeconds": 60,
      "quickLoginCheckMilliSeconds": 1000,
      "maxDeltaTimeSeconds": 43200,
      "failureFactor": 30,
      "defaultRoles": [ "offline_access", "uma_authorization", "user" ],
      "requiredCredentials": [ "password" ],
      "passwordPolicy": "length(8) and notUsername(undefined)",
      "otpPolicyType": "totp",
      "otpPolicyAlgorithm": "HmacSHA1",
      "otpPolicyInitialCounter": 0,
      "otpPolicyDigits": 6,
      "otpPolicyLookAheadWindow": 1,
      "otpPolicyPeriod": 30,
      "browserSecurityHeaders": {
        "contentSecurityPolicy": "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
      },
      "smtpServer": { },
      "eventsEnabled": false,
      "eventsListeners": [ "jboss-logging" ],
      "enabledEventTypes": [ ],
      "adminEventsEnabled": false,
      "adminEventsDetailsEnabled": false,
      "internationalizationEnabled": false,
      "supportedLocales": [ ],
      "browserFlow": "browser",
      "registrationFlow": "registration",
      "directGrantFlow": "direct grant",
      "resetCredentialsFlow": "reset credentials",
      "clientAuthenticationFlow": "clients",
      "dockerAuthenticationFlow": "docker auth",
      "attributes": { },
      "clients": [
        {
          "clientId": "ospo-events-app",
          "enabled": true,
          "redirectUris": [
            "*"
          ],
          "webOrigins": [
            "*"
          ],
          "publicClient": false,
          "protocol": "openid-connect",
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": false,
          "implicitFlowEnabled": false,
          "standardFlowEnabled": true,
          "secret": "client-secret-123"
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "user",
            "description": "User role"
          },
          {
            "name": "admin",
            "description": "Administrator role"
          }
        ]
      }
    }