apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: minio-setup
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mc
        image: minio/mc:RELEASE.2024-04-29T18-08-57Z
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Wait for MinIO to be available
          echo "Waiting for MinIO to be available..."
          until mc alias set myminio http://minio:9000 minioadmin minioadmin 2>/dev/null; do
            echo "MinIO not ready, waiting 5 seconds..."
            sleep 5
          done
          
          # Create bucket if it doesn't exist
          mc mb --ignore-existing myminio/uploads
          
          # Set bucket public policy for anonymous read access
          mc policy set download myminio/uploads
          
          echo "MinIO setup complete"