# Default values for ospo-app chart
replicaCount: 1

appServer:
  image:
    repository: ospo-app
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000
  env:
    NODE_ENV: production
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

postgresql:
  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
  auth:
    username: ospo_user
    password: ospo_password123
    database: ospo_events
    existingSecret: null
  service:
    port: 5432
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  persistence:
    enabled: false

keycloak:
  image:
    repository: quay.io/keycloak/keycloak
    tag: 21.1.2
    pullPolicy: IfNotPresent
  auth:
    existingSecret: null
  service:
    port: 8080
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

minio:
  image:
    repository: minio/minio
    tag: latest
    pullPolicy: IfNotPresent
  auth:
    rootUser: minio
    rootPassword: minio123
    existingSecret: null
  service:
    port: 9000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

sharedVolume:
  enabled: false
  mountPath: /app/shared
  size: 1Gi

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: ospo-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

secrets:
  sessionSecret: null